#!/bin/bash
# ===================================================================
# RNA-Seq Meta-Analyst Pipeline Launcher
# ===================================================================
set -e

# ===================================================================
# HELPER FUNCTIONS
# ===================================================================

function show_help {
    cat << 'EOF'
=== RNA-Seq Meta-Analyst Pipeline Launcher ===

Usage: ./run_pipeline.sh [OPTIONS]

Required Arguments:
  --project-dir    <path>  Absolute path to the project directory.
  --mode           <SE|PE> Sequencing mode: Single-End (SE) or Paired-End (PE).

Path Arguments (auto-detected from --project-dir if standard structure):
  --reads-dir      <path>  Path to raw FASTQ files (default: <project-dir>/data/raw)
  --genome-dir     <path>  Path to genome files (default: <project-dir>/data)
  --sample-info    <path>  Path to sampleinfo.txt (default: <project-dir>/data/sampleinfo.txt)
  --output-dir     <path>  Results directory (default: <project-dir>/results)
  --index-dir      <path>  Optional: Pre-built indices directory

Pipeline Control:
  --skip-alignment      Skip alignment and quantification
  --skip-deg            Skip DEG analysis
  --skip-comparison     Skip comparison analysis
  --deg-only            Only run DEG (requires existing count matrices)
  --comparison-only     Only run comparison (requires existing DEG results)

DEG Thresholds:
  --log2fc <value>      log2 Fold Change threshold (default: 1)
  --fdr <value>         FDR threshold (default: 0.05)
  --pvalue <value>      p-value threshold (default: 0.05)

Other Options:
  --threads        <int>   Number of threads (default: 8)
  --image-name     <name>  Docker image name (default: rnaseqmetaanalyst:latest)
  --detached              Run container in detached mode (background)
  --help                   Show this help message

Examples:
  # Full pipeline
  ./run_pipeline.sh --project-dir $(pwd) --mode PE

  # DEG only (after alignment)
  ./run_pipeline.sh --project-dir $(pwd) --mode PE --deg-only

  # Custom thresholds
  ./run_pipeline.sh --project-dir $(pwd) --mode PE --log2fc 0 --fdr 0.05

Directory Structure:
  project/
    ├── data/
    │   ├── *.fna|*.fa|*.fasta    <- Genome file
    │   ├── *.gtf                  <- Annotation
    │   ├── *.gff|*.gff3          <- Annotation
    │   ├── sampleinfo.txt
    │   └── raw/                   <- FASTQ files
    └── results/                   <- Generated by pipeline

EOF
}

find_file_in_dir() {
    local dir="$1"
    shift
    local patterns=("$@")

    for pattern in "${patterns[@]}"; do
        # Try to find files matching the pattern
        local found=$(find "$dir" -maxdepth 1 -type f -name "$pattern" 2>/dev/null | head -1)
        if [ -n "$found" ]; then
            basename "$found"
            return 0
        fi
    done
    
    # If nothing found, return error
    return 1
}

# ===================================================================
# DEFAULT VALUES
# ===================================================================

THREADS=8
IMAGE_NAME="rnaseqmetaanalyst:latest"
DETACHED_MODE=false
LOG2FC_THRESHOLD=0
FDR_THRESHOLD=0.05
PVALUE_THRESHOLD=0.05
PIPELINE_FLAGS=""

# ===================================================================
# PARSE COMMAND-LINE ARGUMENTS
# ===================================================================

while [[ "$#" -gt 0 ]]; do
    case $1 in
        --project-dir) PROJECT_DIR="$2"; shift ;;
        --reads-dir) HOST_READS_DIR="$2"; shift ;;
        --genome-dir) HOST_GENOME_DIR="$2"; shift ;;
        --sample-info) HOST_SAMPLE_INFO="$2"; shift ;;
        --output-dir) HOST_OUTPUT_DIR="$2"; shift ;;
        --index-dir) HOST_INDEX_DIR="$2"; shift ;;
        --threads) THREADS="$2"; shift ;;
        --mode) MODE="$2"; shift ;;
        --image-name) IMAGE_NAME="$2"; shift ;;
        --detached) DETACHED_MODE=true ;;
        --skip-alignment) PIPELINE_FLAGS+=" --skip-alignment" ;;
        --skip-deg) PIPELINE_FLAGS+=" --skip-deg" ;;
        --skip-comparison) PIPELINE_FLAGS+=" --skip-comparison" ;;
        --deg-only) PIPELINE_FLAGS+=" --deg-only" ;;
        --comparison-only) PIPELINE_FLAGS+=" --comparison-only" ;;
        --log2fc) LOG2FC_THRESHOLD="$2"; PIPELINE_FLAGS+=" --log2fc $2"; shift ;;
        --fdr) FDR_THRESHOLD="$2"; PIPELINE_FLAGS+=" --fdr $2"; shift ;;
        --pvalue) PVALUE_THRESHOLD="$2"; PIPELINE_FLAGS+=" --pvalue $2"; shift ;;
        --help) show_help; exit 0 ;;
        *) echo "ERROR: Unknown parameter: $1"; show_help; exit 1 ;;
    esac
    shift
done

# ===================================================================
# VALIDATE REQUIRED ARGUMENTS
# ===================================================================

if [ -z "$PROJECT_DIR" ] || [ -z "$MODE" ]; then
    echo "ERROR: --project-dir and --mode are required."
    echo ""
    show_help
    exit 1
fi

# Normalize MODE
MODE=$(echo "$MODE" | tr '[:lower:]' '[:upper:]')
if [[ "$MODE" != "SE" && "$MODE" != "PE" ]]; then
    echo "ERROR: --mode must be 'SE' or 'PE', got: $MODE"
    exit 1
fi

# ===================================================================
# SET DEFAULT PATHS
# ===================================================================

HOST_READS_DIR=${HOST_READS_DIR:-"${PROJECT_DIR}/data/raw"}
# Try data/genome first, fall back to data if not found
if [ -d "${PROJECT_DIR}/data/genome" ]; then
    HOST_GENOME_DIR=${HOST_GENOME_DIR:-"${PROJECT_DIR}/data/genome"}
else
    HOST_GENOME_DIR=${HOST_GENOME_DIR:-"${PROJECT_DIR}/data"}
fi
HOST_SAMPLE_INFO=${HOST_SAMPLE_INFO:-"${PROJECT_DIR}/data/sampleinfo.txt"}
HOST_OUTPUT_DIR=${HOST_OUTPUT_DIR:-"${PROJECT_DIR}/results"}

# ===================================================================
# PRE-RUN VALIDATION
# ===================================================================

echo ""
echo "=========================================="
echo "RNA-SEQ PIPELINE LAUNCHER"
echo "=========================================="
echo ""

echo ">>> Performing pre-run checks..."

# Check Docker
if ! command -v docker &> /dev/null; then
    echo "ERROR: Docker not found. Is Docker installed and running?" >&2
    exit 1
fi

# Check Docker image
if ! docker image inspect "$IMAGE_NAME" &> /dev/null; then
    echo "ERROR: Docker image '$IMAGE_NAME' not found" >&2
    echo "       Please build the image first:" >&2
    echo "       docker build -t $IMAGE_NAME ." >&2
    exit 1
fi

# Check directories
if [ ! -d "$HOST_READS_DIR" ]; then
    echo "ERROR: Reads directory not found: $HOST_READS_DIR" >&2
    exit 1
fi

if [ ! -d "$HOST_GENOME_DIR" ]; then
    echo "ERROR: Genome directory not found: $HOST_GENOME_DIR" >&2
    exit 1
fi

if [ ! -f "$HOST_SAMPLE_INFO" ]; then
    echo "ERROR: Sample info file not found: $HOST_SAMPLE_INFO" >&2
    exit 1
fi

echo "[OK] Docker is available"
echo "[OK] Docker image found: $IMAGE_NAME"
echo "[OK] Reads directory: $HOST_READS_DIR"
echo "[OK] Genome directory: $HOST_GENOME_DIR"
echo "[OK] Sample info: $HOST_SAMPLE_INFO"

# ===================================================================
# AUTO-DETECT GENOME FILES
# ===================================================================

echo ""
echo ">>> Auto-detecting genome files..."
echo "    Searching in: $HOST_GENOME_DIR"

# List all files in genome directory for debugging
echo "    Files available:"
ls -lh "$HOST_GENOME_DIR" | tail -n +2 | awk '{print "      - " $9}' | head -10

# Find genome FASTA (try multiple patterns)
GENOME_FASTA=""
for pattern in "*.fna" "*.fa" "*.fasta" "*.fna.gz" "*.fa.gz" "*.fasta.gz"; do
    echo "    Trying pattern: $pattern"
    GENOME_FASTA=$(find "$HOST_GENOME_DIR" -maxdepth 1 -type f -name "$pattern" 2>/dev/null | head -1)
    if [ -n "$GENOME_FASTA" ]; then
        GENOME_FASTA=$(basename "$GENOME_FASTA")
        break
    fi
done

if [ -z "$GENOME_FASTA" ]; then
    echo ""
    echo "ERROR: Genome FASTA file not found in $HOST_GENOME_DIR" >&2
    echo "       Looked for patterns: *.fna, *.fa, *.fasta (also .gz versions)" >&2
    echo ""
    echo "Available files in directory:"
    ls -1 "$HOST_GENOME_DIR"
    exit 1
fi
echo "[OK] Genome FASTA: $GENOME_FASTA"

# Find GTF
GENOME_GTF=""
for pattern in "*.gtf" "*.gtf.gz" "genomic.gtf"; do
    GENOME_GTF=$(find "$HOST_GENOME_DIR" -maxdepth 1 -type f -name "$pattern" 2>/dev/null | head -1)
    if [ -n "$GENOME_GTF" ]; then
        GENOME_GTF=$(basename "$GENOME_GTF")
        break
    fi
done

if [ -z "$GENOME_GTF" ]; then
    echo ""
    echo "ERROR: GTF file not found in $HOST_GENOME_DIR" >&2
    echo "       Looked for patterns: *.gtf, genomic.gtf" >&2
    echo ""
    echo "Available files:"
    ls -1 "$HOST_GENOME_DIR"
    exit 1
fi
echo "[OK] GTF: $GENOME_GTF"

# Find GFF
GENOME_GFF=""
for pattern in "*.gff" "*.gff3" "*.gff.gz" "*.gff3.gz" "genomic.gff"; do
    GENOME_GFF=$(find "$HOST_GENOME_DIR" -maxdepth 1 -type f -name "$pattern" 2>/dev/null | head -1)
    if [ -n "$GENOME_GFF" ]; then
        GENOME_GFF=$(basename "$GENOME_GFF")
        break
    fi
done

if [ -z "$GENOME_GFF" ]; then
    echo ""
    echo "ERROR: GFF file not found in $HOST_GENOME_DIR" >&2
    echo "       Looked for patterns: *.gff, *.gff3, genomic.gff" >&2
    echo ""
    echo "Available files:"
    ls -1 "$HOST_GENOME_DIR"
    exit 1
fi
echo "[OK] GFF: $GENOME_GFF"

# Count FASTQ files
FASTQ_COUNT=$(find "$HOST_READS_DIR" -type f \( -name "*.fastq.gz" -o -name "*.fq.gz" \) 2>/dev/null | wc -l)
if [ "$FASTQ_COUNT" -eq 0 ]; then
    echo ""
    echo "ERROR: No FASTQ files found in $HOST_READS_DIR" >&2
    echo ""
    echo "Files in reads directory:"
    ls -1 "$HOST_READS_DIR" | head -10
    exit 1
fi
echo "[OK] Found $FASTQ_COUNT FASTQ files"

# ===================================================================
# CREATE OUTPUT DIRECTORY
# ===================================================================

mkdir -p "$HOST_OUTPUT_DIR"
echo "[OK] Results directory: $HOST_OUTPUT_DIR"

# ===================================================================
# PREPARE DOCKER VOLUMES AND ENVIRONMENT
# ===================================================================

echo ""
echo ">>> Preparing Docker configuration..."

# Base Docker arguments
DOCKER_ARGS="--rm"

# Add detached mode if requested
if [ "$DETACHED_MODE" = true ]; then
    DOCKER_ARGS+=" -d"
fi

# Volume mounts
DOCKER_ARGS+=" -v ${HOST_READS_DIR}:/data/reads:ro"
DOCKER_ARGS+=" -v ${HOST_GENOME_DIR}:/data/genome:ro"
DOCKER_ARGS+=" -v ${HOST_SAMPLE_INFO}:/data/sampleinfo.txt:ro"
DOCKER_ARGS+=" -v ${HOST_OUTPUT_DIR}:/data"

# Optional: Mount pre-built indices
if [ -n "$HOST_INDEX_DIR" ] && [ -d "$HOST_INDEX_DIR" ]; then
    echo "[OK] Mounting pre-built indices: $HOST_INDEX_DIR"
    DOCKER_ARGS+=" -v ${HOST_INDEX_DIR}:/indices:ro"
    DOCKER_ARGS+=" -e INDEX_DIR=/indices"
fi

# Environment variables
DOCKER_ARGS+=" -e THREADS=$THREADS"
DOCKER_ARGS+=" -e MODE=$MODE"
DOCKER_ARGS+=" -e READ_DIR=/data/reads"
DOCKER_ARGS+=" -e GENOME_DIR=/data/genome"
DOCKER_ARGS+=" -e TRIM_DIR=/data/Trim"
DOCKER_ARGS+=" -e GTF=/data/genome/$GENOME_GTF"
DOCKER_ARGS+=" -e FASTA=/data/genome/$GENOME_FASTA"
DOCKER_ARGS+=" -e GFF=/data/genome/$GENOME_GFF"
DOCKER_ARGS+=" -e LOG2FC_THRESHOLD=$LOG2FC_THRESHOLD"
DOCKER_ARGS+=" -e FDR_THRESHOLD=$FDR_THRESHOLD"
DOCKER_ARGS+=" -e PVALUE_THRESHOLD=$PVALUE_THRESHOLD"

# ===================================================================
# DISPLAY CONFIGURATION
# ===================================================================

echo ""
echo "Configuration Summary:"
echo "  Image:          $IMAGE_NAME"
echo "  Mode:           $MODE"
echo "  Threads:        $THREADS"
echo "  Log2FC:         $LOG2FC_THRESHOLD"
echo "  FDR:            $FDR_THRESHOLD"
echo "  Genome FASTA:   $GENOME_FASTA"
echo "  GTF:            $GENOME_GTF"
echo "  GFF:            $GENOME_GFF"
echo "  Pipeline flags: $PIPELINE_FLAGS"
echo ""

# ===================================================================
# RUN THE CONTAINER
# ===================================================================

echo ">>> Launching container..."
echo ""

if [ "$DETACHED_MODE" = true ]; then
    # Run container in background
    CONTAINER_ID=$(docker run $DOCKER_ARGS "$IMAGE_NAME" \
        /bin/bash -c "/opt/project/scripts/master.sh $PIPELINE_FLAGS")
    
    LOG_FILE="${HOST_OUTPUT_DIR}/pipeline_run.log"

    echo "=========================================="
    echo "✅ CONTAINER STARTED IN BACKGROUND"
    echo "=========================================="
    echo ""
    echo "Container ID: $CONTAINER_ID"
    echo ""
    echo "The pipeline will continue to run even if you close this terminal."
    echo "Logs are being saved to: $LOG_FILE"
    echo ""
    echo "To monitor progress:"
    echo "  docker logs -f $CONTAINER_ID"
    echo ""
    echo "Or view the log file:"
    echo "  tail -f $LOG_FILE"
    echo ""
    echo "To stop the container:"
    echo "  docker stop $CONTAINER_ID"
    echo ""
    
    # Save container ID to file for later reference
    echo "$CONTAINER_ID" > "${HOST_OUTPUT_DIR}/container_id.txt"
    echo "Container ID saved to: ${HOST_OUTPUT_DIR}/container_id.txt"
    echo ""
    
    # Start saving logs in the background (redirect to log file, not terminal)
    docker logs -f "$CONTAINER_ID" > "$LOG_FILE" 2>&1 &
    LOG_PID=$!
    echo "Log streaming PID: $LOG_PID"
    echo ""

else
    # Interactive mode - show output in terminal AND save to log
    LOG_FILE="${HOST_OUTPUT_DIR}/pipeline_run.log"
    
    # Run container and tee output to both terminal and log file
    docker run $DOCKER_ARGS "$IMAGE_NAME" \
        /bin/bash -c "/opt/project/scripts/master.sh $PIPELINE_FLAGS" 2>&1 | tee "$LOG_FILE"

    EXIT_CODE=${PIPESTATUS[0]}

    echo ""
    if [ $EXIT_CODE -eq 0 ]; then
        echo "=========================================="
        echo "✅ PIPELINE COMPLETED SUCCESSFULLY"
        echo "=========================================="
        echo ""
        echo "Results location: $HOST_OUTPUT_DIR"
        echo "Full log saved to: $LOG_FILE"
    else
        echo "=========================================="
        echo "❌ PIPELINE FAILED"
        echo "=========================================="
        echo ""
        echo "Exit code: $EXIT_CODE"
        echo "Check logs at: $LOG_FILE"
        echo "Or check: $HOST_OUTPUT_DIR/logs/"
    fi

    exit $EXIT_CODE
fi
