name: 16_ppl_bioinfo-env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  # Core language versions
  - python=3.8
  - r-base=4.3.2
  - conda=23.7.2

  # Quality control tools
  - fastqc=0.11.9
  - fastp=0.23.2
  - multiqc=1.14

  # rRNA filtering
  - sortmerna=2.1b

  # Aligners
  - hisat2=2.2.1
  - star=2.7.3a
  - bowtie2=2.3.5.1

  # Quantification
  - subread=2.0.0         # for FeatureCounts
  - htseq=0.13.5
  - rsem=1.3.1

  # File handling
  - samtools=1.13

  # R packages (ensure compatibility with r-base=4.3.2)
  - r-dplyr=1.1.4
  - r-openxlsx=4.2.5.2
  - r-tidyverse=2.0.0

  # Bioconductor packages
  - bioconductor-deseq2=1.42.0
  - bioconductor-edger=3.42.4
