name: rnaseq-cli
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - fastqc=0.11.9
  - fastp=0.23.2
  - multiqc=1.14
  - sortmerna=2.1b
  - hisat2=2.2.1
  - star=2.7.10b
  - bowtie2=2.4.5
  - subread=2.0.6
  - htseq=0.13.5
  - rsem=1.3.3
  - samtools=1.15.1
  - pigz
  - parallel
