name: 16_ppl_bioinfo-env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  # Base
  - python=3.8
  - conda
  - r-base=4.3.2

  # QC tools
  - fastqc=0.11.9
  - fastp=0.23.2
  - multiqc=1.14

  # Filtering
  - sortmerna=2.1b

  # Aligners (use compatible recent versions)
  - hisat2=2.2.1
  - star=2.7.10b
  - bowtie2=2.4.5

  # Quantification
  - subread=2.0.6      # FeatureCounts
  - htseq=0.13.5
  - rsem=1.3.3         
  - samtools=1.15.1    
  
  # R packages
  - r-dplyr=1.1.4
  - r-openxlsx=4.2.5.2
  - r-tidyverse=2.0.0

  # Bioconductor tools
  - bioconductor-deseq2=1.42.0
  - bioconductor-edger=3.42.4
