name: 16_ppl_bioinfo-env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - fastqc=0.11.9
  - multiqc=1.8
  - sortmerna=2.1b
  - fastp=0.23.2
  - hisat2=2.2.1
  - star=2.7.3a
  - bowtie2=2.3.5.1
  - subread=2.0.0            
  - htseq=0.13.5
  - rsem=1.3.1
  - samtools=1.13
  - r-base
  - bioconductor-deseq2
  - bioconductor-edger
  - python=3.8
  
