name: 16_ppl_bioinfo-env

channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - conda
  - r-base=4.2.3

  # Quality Control Tools
  - fastqc=0.11.9
  - fastp=0.23.2
  - multiqc=1.14

  # rRNA Filtering
  - sortmerna=2.1b

  # Aligners
  - hisat2=2.2.1
  - star=2.7.10b
  - bowtie2=2.4.5

  # Quantification Tools
  - subread=2.0.6
  - htseq=0.13.5
  - rsem=1.3.3
  - samtools=1.15.1

  # R packages (CRAN)
  - r-dplyr
  - r-openxlsx
  - r-tidyverse

  # Bioconductor Core (compatible with R 4.2.3, Bioc 3.16)
  - bioconductor-deseq2
  - bioconductor-edger
  - bioconductor-genomeinfodb
  - bioconductor-biobase
  - bioconductor-s4vectors
  - bioconductor-summarizedexperiment
  - bioconductor-biocgenerics
  - bioconductor-matrixgenerics
